[workspace]
members = [
  "compiler",
  "frontend/lexer",
  "frontend/parser",
  "backend/codegen",
  "backend/codegen/cranelift"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
