[package]
name = "tangic"
version.workspace = true
edition.workspace = true

[dependencies]
tangic_parser.workspace = true
miette.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing.workspace = true
