[package]
name = "tangic_lexer"
version.workspace = true
edition.workspace = true

[dependencies]
logos = "0.13.0"
thiserror.workspace = true
miette.workspace = true
derive_more.workspace = true
paste = "1.0.14"
